#!/usr/bin/env bash

parent_path=$1
supported_major_versions="10.4 10.5 10.6 5.6 5.7 8.0"
log_file=$parent_path/collector.log
output_dir=$parent_path/collection_output
query_digest_file=$output_dir/query_digest.txt
